version: "3.8"

services:
  backend:
    image: "dryflowery/halla-univ-chatbot-backend:latest"
    container_name: chatbot_backend
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - PORT=3000
    networks:
      - app-network
    restart: always

  nginx:
    image: "dryflowery/halla-univ-chatbot-nginx:latest"
    container_name: chatbot_nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
